### ISSUE TITLE
Temple of the Jade Serpent Unable to be made

### ISSUE THREAD

**Issue by DrTobogganMD** [Wotuu/keystone.guru#1517]
When attempting to make a route for Temple, "Invalid Dungeon ID" is returned.

**Comment by Wotuu** [comment]
Hi, this has been fixed a few days ago (probably not long after you made this issue). This is due to the Mists of Pandaria expansion not being enabled. I ticked it on, but every time I did a deployment it kept flipping off again. I sorted that out now so it should stay open.

There's still an issue where the entire 2nd floor is missing. See the discussion about that here: https://github.com/Nnoggie/MythicDungeonTools/issues/405. I'll keep this ticket as a reference on my side and will update it accordingly.

**Comment by DrTobogganMD** [comment]
Thanks, I was able to make a route now and just note the missing pulls via some drawings!

**Comment by DrTobogganMD** [comment]
So I was going over the route I did make: https://keystone.guru/route/temple-of-the-jade-serpent/AcBbwZf/temple-of-the-jade-serpent-s1

The only thing that seems to be missing are the 3 packs i've circled near the final boss. There really isn't an upper floor needed - the mobs on the "upper floor" of the library are present, just all on one layer. Just some more info for you. :D

**Comment by Wotuu** [comment]
I've gotten around to adding the missing packs here: https://github.com/Nnoggie/MythicDungeonTools/pull/409

I also came to that same conclusion here: https://github.com/Nnoggie/MythicDungeonTools/issues/405

Thanks for thinking along :)

**Comment by Wotuu** [comment]
It was just merged at MDT and I will push an update tonight most likely to fix this issue on my side as well. Closing for now!
