### ISSUE TITLE
Newly published routes bugged on some Maps

### ISSUE THREAD

**Issue by AgentHawk** [Wotuu/keystone.guru#1600]
Hey

some Maps show them and some not (Newly published routes).

Like AA is fine but CoS is buged.

Greetings

**Comment by Wotuu** [comment]
Hey, thanks for bringing this to my attention. The issue is that the `new` section does not account for seasons. You're only seeing Dragonflight dungeons there. I will correct that. I also noticed that clicking `Popular routes by next affixes` etc suffer from the same problem so I'll try to correct that as well. Cheers!

**Comment by Wotuu** [comment]
I just added new pages to fix this issue. Will deploy this later this week as I'm sorta in the middle of another feature which I can't release just yet. Thanks again for notifying me!
