### ISSUE TITLE
Beguiling Mob Percent & Mob tether

### ISSUE THREAD

**Issue by tectas** [Wotuu/keystone.guru#235]
A little Late in the Patch, but still about a month to go, so maybe it's still relevant.
Beguiling emissaries do give Mob % too, but show up as 0, but that's only true for enchanted emissaries, void and tides both give about 4, unfotunately not that clear cut, but still better than nothing.
Here is the related article (and also from experience they do indeed count to the total mobs killed).
https://www.wowhead.com/news=292447/mythic-dungeon-mob-count-changes-2-beguiling-emissaries-now-give-count

Additionally, Emissaries aren't tethered to any group, but always stand by themselves.
In many cases they indeed will be pulled too through social aggro, but with some tricks it can be avoided and therefore it would be neat being able to add them to their own kill, instead only being able to mark them with the group they're in.

**Comment by Wotuu** [comment]
I suspected emissaries aren't explicitly tied to groups even though Blizzard explicitly stated they are. Unfortunately in Keystone.guru they are wired to be attached to a group. But fortunately if necessary I can create special groups for them and tie them to that group instead, as I have done for some Emissaries that are on their own with no other group around them.

Enemy %-age are easy to correct, though again it's a bit of a problem for emissaries since the enemy ID they have defines a bunch of properties, one of which is enemy count. In short, I cannot change enemy counts _per dungeon_ since that'd require a different ID as is normally the case. But again, I can work around that by doing some magic which will not be too pretty server-side.

I've looked at a lot of streams back in August about the %-age of the emissaries and none of them actually gave any %-age. Are you sure they're giving %-age now on live? I haven't played a M+ in some time so I don't know unless I start checking some streams again! The source you linked is from June, hence my doubts :)

**Comment by tectas** [comment]
I do m+ almost every day (not that much of a high key pusher though, about 15 is my max soo...), and they are defenitely not tied to the group. You can do some nifty pulls in atal or the underrot, where you pull a mob outside of the emissaries social aggro range without also pulling it, or with usage of ring of peace to get it out of social aggro range.
Here is an article:
https://www.wowhead.com/news=295130/tides-emissary-beguiling-tip-1-emissaries-arent-linked
It mostly refers to tides, but the same applies to void and enchanted.

About the %:
Here is a newer article, it is from july, though has been updated in september with the mob count portion at the bottom.
https://www.wowhead.com/guides/beguiling-affix-guide-battle-for-azeroth-season-3-mythic-affix#beguiling-count

**Comment by Wotuu** [comment]
Thing is, there's no such thing as the 'default' %-age that an enemy should get per dungeon, yet. I can define this manually if need be by attaching it to the dungeon I think. This too should not be difficult to achieve.

I'll create some tickets in a bit to tackle some of these issues. Cheers!

**Comment by tectas** [comment]
You missunderstood me, the default I'm refering to is 4, which fits for most dungeons for tides and voids. Only at shrine and TD the % per emissary differs, which isn't optimal, but should be neglectable.

**Comment by Wotuu** [comment]
Hi,

I'm closing this ticket since Beguiling is no longer a thing. Things are slowly calming down on my end (for as far as that's possible with babies) and I'm looking to perform some more work again on the website. If you have any other things to report, do not hesitate to create a ticket!
