### ISSUE TITLE
Buttons are hidden by ad-blockers (uBlock)

### ISSUE THREAD

**Issue by Wotuu** [Wotuu/keystone.guru#28]
For some reason, ad blockers may or may not hide all orange buttons on the website. Figure out why they do this and fix it.

https://www.reddit.com/r/CompetitiveWoW/comments/9meu1c/introducing_keystoneguru_plan_your_m_routes_online/e7efd5l

**Comment by okiehsch** [comment]
That was caused by a [faulty commit](https://github.com/uBlockOrigin/uAssets/commit/d2c52eee0a7fbb334f08696a4d7b166fe15c7824), which was only "live" for a [few hours](https://github.com/uBlockOrigin/uAssets/commit/efb98870510f5731b53f45f2bb76723eb3b31188).
If some of your users have received the faulty commit they can manually update their filter list to fix the issue.
The list also auto-updates every 4 days, so everybody will eventually get the correct filters.

**Comment by Wotuu** [comment]
Awesome! Thanks for posting that, I'd have spent a bunch of time trying to figure this one out. The best bugs are the ones you don't have to fix yourself :)
