### ISSUE TITLE
Patrol visibility is reset on floor change

### ISSUE THREAD

**Issue by Mazorlion** [Wotuu/keystone.guru#510]
Steps to reproduce:
1) Go to Necrotic Wake floor 1
2) Disable Visibility for `Patrol` in `Map Elements`
3) Change to `The Stitchworks` by clicking on the floor icon in the map

Patrol is now showing on the map but remains unchecked in the `Map Elements` dropdown.

Side note that the floor also doesn't change in the `Floor` selection on the left.

**Comment by Wotuu** [comment]
Hi! Thank you for both issue reports - I'll check it out right now 👍

**Comment by Wotuu** [comment]
Hi, I have resolved the issue you're describing. I have also fixed an issue where if you untick patrols, it would also untick enemies (though it would still display them due to yet another issue). All of those issues should be resolved now, thanks again for bringing this to my attention! I don't tend to use the feature often :)
