### ISSUE TITLE
Percentage/count toggle doesn’t affect NPC icons

### ISSUE THREAD

**Issue by liamwye** [Wotuu/keystone.guru#624]
Is it possible to have the NPC icons toggle between the count and percentage values with the rest of the UI? It's currently super annoying not being able to glance at a pack and see the percentage.

**Comment by Wotuu** [comment]
Hi, this would be possible but I didn't implement it yet since the rendering of the percentage is a longer string than is currently 'possible' in the enemies. Like right now I can render a `5` easily, but `5.12%` would look very ugly. But I can check this out and do some reworking if this is important for you 👍
