### ISSUE TITLE
Expanded display of pull not showing individual mob percentage/points

### ISSUE THREAD

**Issue by allygator** [Wotuu/keystone.guru#776]
Im not sure if this was intentionally removed in the update, but its useful to know the % of an individual mob in a pull. Specifically for prideful knowing which mobs will go over the breakpoint is important. If this was intentionally removed, this issue is a request to readd this feature.

The expanded view of a pull only contains "Add kill area", pull color, and delete.

**Comment by Wotuu** [comment]
Hi, yes this was removed since the information wasn't deemed too useful and took up too much space. The enemy listing has been moved to the same row as the button to expand (as you know).

That said - I do think you have a point. Would it work for you if you can mouse over the enemy portraits and be able to see the enemy forces+percentages in there? Right now it just displays the enemy name, I can add something like this:

```
Risen Bonesoldier (+4/ +1%)
```

**Comment by allygator** [comment]
I do agree that it took up a lot of space. Yes, mouse over on portraits would be good!
