### ISSUE TITLE
Excessive gradient notifications

### ISSUE THREAD

**Issue by omicron-o** [Wotuu/keystone.guru#907]
Whenever you change the pull gradient in settings > pull settings > pull color gradient you get an excessive amount of notifications that keeps coming for up to several minutes. I suspect just dragging one of the gradient sliders around will trigger this behavior.

**Comment by Wotuu** [comment]
Oh very interesting - I will fix this, thanks for reporting!

**Comment by Wotuu** [comment]
Fixed - I have also removed the notification since I kind of feel like it's redundant anyways, plus still a bit spammy if you're actively editing the gradient. You were correct - dragging the slider triggered an event which prompted the save to both local storage and the server, causing all the notifications. Not sure why this suddenly started happening - possibly a library upgrade that I did and didn't catch this. But either way - solved for next release!
